#!/usr/bin/env bash

read -p "Are you sure? (Ctrl-c to exit)"

rm -rf ~/.bash_sessions/*

_files=(
  ~/.bash_history
  ~/.sh_history
  ~/.zsh_history
  ~/.zhistory

  ~/.node_repl_history
  ~/.coffee_history
  ~/.python_history
  ~/.utop-history
  ~/.rtop-history

  ~/.lesshst

  ~/.mysql_history
  ~/.psql_history
  ~/.rediscli_history

  # ~/.local/share/fish/fish_history

  ~/.slime_paste
)

for file in ${_files[@]}; do
  if [ -s $file ]; then
    echo "> $file"
    cp /dev/null $file
  fi
done
