complete -c 0x0 -l curl-args -d 'Pass remaining arguments to curl'
complete -c 0x0 -l delete -d 'Remove the pasted file; requires --token'
complete -c 0x0 -l dry-run -d 'Output the curl command without doing any requests'
complete -c 0x0 -l no-secret -d 'Do not make the file URL secret'
complete -c 0x0 -l version -d 'Display version and exit'
complete -c 0x0 -s T -l show-token -d 'Also display the management token'
complete -c 0x0 -s c -l copy -d 'Automatically copy the file URL'
complete -c 0x0 -s d -l expire-date -r -d 'Set the expiration date of the file'
complete -c 0x0 -s e -l expires-in -r -d 'Set the lifetime of the file'
complete -c 0x0 -s h -l help -d 'Display help and exit'
complete -c 0x0 -s i -l instance -r -d 'Set a custom server instead of https://0x0.st'
complete -c 0x0 -s n -l name -r -d 'Set the name of the file sent to 0x0.st'
complete -c 0x0 -s t -l token -r -d 'Set the management token'
complete -c 0x0 -s v -l verbose -d 'Verbose output'
